version: '3.8'
services:
  transform:
    environment:
      - DATABASE_URL=postgresql://codetest:password@database/codetest
    networks:
      - test_network
    build: 
      context: .
      dockerfile: Dockerfile # only needed if your Dockerfile has a different name or is in a different directory
    image: transform:latest
    volumes:
      - ./data:/data
    # ports:
    #   - "8000:8000"
    # other settings like ports, environment variables, etc.
networks:
  test_network:
    external: true